apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: dotnet-webapi
  name: dotnet-webapi
spec:
  replicas: 1
  selector:
    io.kompose.service: dotnet-webapi
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dotnet-webapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_HTTPS_PORT
          value: "5001"
        - name: DB_CONNECTION_STRING
          value: host=postgres;port=5432;database=postgres;username=postgres;password=postgres
        - name: JWT_SIGNING_KEY
          value: SdqlA0Y5e6HMAK1wm6iHHHz2u37XGtlo
        image: ' '
        name: primeapi
        ports:
        - containerPort: 80
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - primeapi
      from:
        kind: ImageStreamTag
        name: dotnet-webapi:latest
    type: ImageChange
status: {}
