apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: dotnet-webapi
  name: dotnet-webapi
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    io.kompose.service: dotnet-webapi
status:
  loadBalancer: {}
